
language: python
python:
- "3.6"

before_script:
- wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_win32.zip
- unzip chromedriver_win32.zip -d /home/travis/virtualenv/python3.6.3/bin
- export CHROME_BIN=chromium-browser
script:
- python testing.py